mkdir mutated_candidates
mkdir ./mutated_candidates/mutated_code1
mkdir ./mutated_candidates/mutated_code1_2
mkdir ./mutated_candidates/mutated_code1_3
mkdir ./mutated_candidates/mutated_code1_7
mkdir ./mutated_candidates/mutated_code1_2_3
mkdir ./mutated_candidates/mutated_code1_2_7
mkdir ./mutated_candidates/mutated_code1_3_7
mkdir ./mutated_candidates/mutated_code1_2_3_7
mkdir ./mutated_candidates/mutated_code12
mkdir ./mutated_candidates/mutated_code12_2
mkdir ./mutated_candidates/mutated_code12_3
mkdir ./mutated_candidates/mutated_code12_7
mkdir ./mutated_candidates/mutated_code12_2_3
mkdir ./mutated_candidates/mutated_code12_2_7
mkdir ./mutated_candidates/mutated_code12_3_7
mkdir ./mutated_candidates/mutated_code12_2_3_7
mkdir ./mutated_candidates/mutated_code1_12
mkdir ./mutated_candidates/mutated_code1_12_2
mkdir ./mutated_candidates/mutated_code1_12_3
mkdir ./mutated_candidates/mutated_code1_12_7
mkdir ./mutated_candidates/mutated_code1_12_2_3
mkdir ./mutated_candidates/mutated_code1_12_2_7
mkdir ./mutated_candidates/mutated_code1_12_3_7
mkdir ./mutated_candidates/mutated_code1_12_2_3_7
mkdir ./mutated_candidates/mutated_code2
mkdir ./mutated_candidates/mutated_code2_3
mkdir ./mutated_candidates/mutated_code2_7
mkdir ./mutated_candidates/mutated_code2_3_7
mkdir ./mutated_candidates/mutated_code3
mkdir ./mutated_candidates/mutated_code3_7
mkdir ./mutated_candidates/mutated_code7